name: Build and Prerelease

on:
  push:
    tags:
      - "*.*.*-*"

jobs:
  build-prerelease:
    runs-on: act-latest
    env:
      ARTIFACT_NAME: llm_companion
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - name: Set numeric package version
        run: pnpm pkg set version=0.0.0
      - run: WXT_RELEASE_VERSION=${{ github.ref_name }} pnpm run zip
      - run: WXT_RELEASE_VERSION=${{ github.ref_name }} pnpm run zip:firefox
      - name: Copy artifacts
        run: |
          mkdir -p /upload
          mv .output/*.zip /upload
      - uses: actions/forgejo-release@v2.11.1
        with:
          direction: upload
          url: https://forgejo.o-st.dev
          repo: ST_Consultancy/Llm_companion
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          release-dir: /upload
          prerelease: true
          release-notes-file: release-notes/${{ github.ref_name }}.md
          override: true
