name: Test CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: act-latest
    env:
      EXTENSION_ARTIFACT_NAME: llm_companion
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm exec eslint src --ext .ts,.tsx
      - run: pnpm test
      - run: pnpm run zip
      - run: pnpm run zip:firefox
      - name: Renovate
        uses: https://github.com/renovatebot/github-action@v46.1.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: forgejo
          RENOVATE_ENDPOINT:  https://${{ vars.REGISTRY_URL }}/api/v1
          RENOVATE_AUTODISCOVER: true