name: Test CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: act-latest
    env:
      EXTENSION_ARTIFACT_NAME: llm_companion
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install
      - run: pnpm exec eslint src --ext .ts,.tsx
      - run: pnpm test
      - run: pnpm run zip
      - run: pnpm run zip:firefox
