name: Test CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EXTENSION_ARTIFACT_NAME: llm_companion
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm exec eslint . --ext .ts,.tsx
      - run: pnpm test
      - run: pnpm exec wxt build --target=chrome-mv3
      - run: pnpm exec wxt build --target=firefox
      - run: pnpm exec wxt zip --target=chrome-mv3 --name $EXTENSION_ARTIFACT_NAME
      - run: pnpm exec wxt zip --target=firefox --name $EXTENSION_ARTIFACT_NAME
